resume_directory: ./data/input
summary_output_directory: ./data/output
# data_schema_dir: ./data/schema

segment_keywords:
 education_keywords:
  - 教育经历
  - 教育背景

 work_experience_keywords:
  - 科研与实习
  - ⼯作经历
  - 工作经历
  - 工作背景
  - 实习经历
  - 实习经验
  - 实习背景
  - 实习/实践经历
  - 实习实践经历

 project_keywords:
  - 学生工作与实践
  - 社团/项目经历
  - 社团和组织经历
  - 项目经验
  - 项目经历
  - 实践经历
  - 项目实践
  - 学术经历
  - 科研经历
  - 社团经历
  - 科研项目
  - 校园经历
  - 学校经历

 other_keywords:
  - 技能/证书及其他
  - 语⾔能⼒
  - 语言能力
  - 兴趣爱好
  - 兴趣爱好
  - 技能/语言
  - 兴趣/特长
  - 资格技能
  - 技能
  - 语言
  - 专业技能
  - 技能证书
  - 荣誉与奖励
  - 竞赛经历
  - 所获证书
  - 获奖经历
  - 荣誉证书
  - 获奖情况
  - 资质
  - 证书
  - 个人简介
  - ⾃我评价
  - 自我评价
  - 自我描述
  - 个人总结
  - 其他
  - 技能/证书及其他

other_segment_keywords:
 skills_language_keywords:
  - 技能/证书及其他
  - 语⾔能⼒
  - 语言能力
  - 兴趣爱好
  - 兴趣爱好
  - 技能/语言
  - 兴趣/特长
  - 资格技能
  - 技能
  - 语言
  - 专业技能
  - 技能证书
  
 awards_keywords:
  - 技能/证书及其他
  - 荣誉与奖励
  - 竞赛经历
  - 所获证书
  - 获奖经历
  - 荣誉证书
  - 获奖情况
  - 资质
  - 证书
 
 self_evaluation_keywords:
  - 个人简介
  - ⾃我评价
  - 自我评价
  - 自我描述
  - 个人总结